# Generated by Django 5.2.5 on 2025-08-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
